#!/usr/bin/env Rscript

install.packages("curl", repos="http://cran.us.r-project.org")
install.packages("openssl", repos="http://cran.us.r-project.org")
install.packages("devtools", repos="http://cran.us.r-project.org")
install.packages("optparse", repos="http://cran.us.r-project.org")
install.packages("plyr", repos="http://cran.us.r-project.org")
install.packages("ggplot2", repos="http://cran.us.r-project.org")
install.packages("ggdendro", repos="http://cran.us.r-project.org")
install.packages("philentropy", repos="http://cran.us.r-project.org")
install.packages("R.utils", repos="http://cran.us.r-project.org")
install.packages("xtable", repos="http://cran.us.r-project.org")
install.packages("vegan", repos="http://cran.us.r-project.org")
install.packages("hash", repos="http://cran.us.r-project.org")
install.packages("ape", repos="http://cran.us.r-project.org")
install.packages("devtools", repos="http://cran.us.r-project.org")
library(devtools)
install_github("igraph/rigraph")
install.packages("networkD3", repos="http://cran.us.r-project.org")
